package com.mandar.core;

import static org.lwjgl.glfw.GLFW.*;

public enum KeyCode {
    //Keyboard Keys (Numbers)
    KEY_0(GLFW_KEY_0), KEY_1(GLFW_KEY_1), KEY_2(GLFW_KEY_2), KEY_3(GLFW_KEY_3), KEY_4(GLFW_KEY_4), KEY_5(GLFW_KEY_5),
    KEY_6(GLFW_KEY_6), KEY_7(GLFW_KEY_7), KEY_8(GLFW_KEY_8), KEY_9(GLFW_KEY_9),

    //Keyboard Keys (Letters)
    A(GLFW_KEY_A), B(GLFW_KEY_B), C(GLFW_KEY_C), D(GLFW_KEY_D), E(GLFW_KEY_E), F(GLFW_KEY_F), G(GLFW_KEY_G),
    H(GLFW_KEY_H), I(GLFW_KEY_I), J(GLFW_KEY_J), K(GLFW_KEY_K), L(GLFW_KEY_L), M(GLFW_KEY_M), N(GLFW_KEY_N),
    O(GLFW_KEY_O), P(GLFW_KEY_P), Q(GLFW_KEY_Q), R(GLFW_KEY_R), S(GLFW_KEY_S), T(GLFW_KEY_T), U(GLFW_KEY_U),
    V(GLFW_KEY_V), W(GLFW_KEY_W), X(GLFW_KEY_X), Y(GLFW_KEY_Y), Z(GLFW_KEY_Z),

    //Keyboard Keys (Special)
    APOSTROPHE(GLFW_KEY_APOSTROPHE),
    BACKSLASH(GLFW_KEY_BACKSLASH), BACKSPACE(GLFW_KEY_BACKSPACE),
    CAPS_LOCK(GLFW_KEY_CAPS_LOCK), COMMA(GLFW_KEY_COMMA),
    DELETE(GLFW_KEY_DELETE), DOWN(GLFW_KEY_DOWN),
    END(GLFW_KEY_END), ESCAPE(GLFW_KEY_ESCAPE), EQUAL(GLFW_KEY_EQUAL), ENTER(GLFW_KEY_ENTER),
    F1(GLFW_KEY_F1), F2(GLFW_KEY_F2), F3(GLFW_KEY_F3),  F4(GLFW_KEY_F4),  F5(GLFW_KEY_F5), F6(GLFW_KEY_F6),
    F7(GLFW_KEY_F7),  F8(GLFW_KEY_F8),  F9(GLFW_KEY_F9),  F10(GLFW_KEY_F10), F11(GLFW_KEY_F11), F12(GLFW_KEY_F12),
    F13(GLFW_KEY_F13), F14(GLFW_KEY_F14), F15(GLFW_KEY_F15), F16(GLFW_KEY_F16), F17(GLFW_KEY_F17), F18(GLFW_KEY_F18),
    F19(GLFW_KEY_F19), F20(GLFW_KEY_F20), F21(GLFW_KEY_F21), F22(GLFW_KEY_F22), F23(GLFW_KEY_F23), F24(GLFW_KEY_F24),
    F25(GLFW_KEY_F25),
    GRAVE_ACCENT(GLFW_KEY_GRAVE_ACCENT),
    HOME(GLFW_KEY_HOME),
    INSERT(GLFW_KEY_INSERT),
    

    ;
    //Setup KeyCode Abstraction
    private final int keyCode;
    KeyCode(int keyCode){
        this.keyCode = keyCode;
    }

    public int getKeyCode() {
        return keyCode;
    }
}
